# Generated by Django 5.0.6 on 2024-05-19 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IpsProjects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_title', models.CharField(max_length=30)),
                ('project_time_city', models.CharField(max_length=33)),
                ('project_address', models.CharField(max_length=66)),
                ('project_main_image', models.ImageField(upload_to='img/%y%m%d%H%M')),
                ('project_details', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('project_img_1', models.ImageField(blank=True, null=True, upload_to='img/%y%m%d%H%M%=')),
                ('project_img_2', models.ImageField(blank=True, null=True, upload_to='img/%y%m%d%H%M')),
                ('project_img_3', models.ImageField(blank=True, null=True, upload_to='img/%y%m%d%H%M')),
                ('project_img_4', models.ImageField(blank=True, null=True, upload_to='img/%y%m%d%H%M')),
                ('project_img_5', models.ImageField(blank=True, null=True, upload_to='img/%y%m%d%H%M')),
                ('project_img_6', models.ImageField(blank=True, null=True, upload_to='img/%y%m%d%H%M')),
            ],
        ),
    ]
