# Generated by Django 5.0.6 on 2024-05-21 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ipsprojects',
            name='is_coffe_restaurant',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ipsprojects',
            name='is_facade',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ipsprojects',
            name='is_home_villa',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ipsprojects',
            name='is_office',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ipsprojects',
            name='is_zero_to_hundred',
            field=models.BooleanField(default=False),
        ),
    ]
