# Generated by Django 5.0.6 on 2024-05-31 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_ipsprojects_is_coffe_restaurant_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ipsprojects',
            name='project_img_1',
            field=models.ImageField(blank=True, null=True, upload_to='img/%y%m%d%H%M'),
        ),
    ]
