# Generated by Django 5.0.6 on 2024-06-17 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_alter_ipsprojects_project_img_1'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ipsprojects',
            options={'verbose_name': 'پروژه', 'verbose_name_plural': 'پروژه ها'},
        ),
        migrations.AlterField(
            model_name='ipsprojects',
            name='is_coffe_restaurant',
            field=models.BooleanField(default=False, verbose_name='رستوران و کافه'),
        ),
        migrations.AlterField(
            model_name='ipsprojects',
            name='is_facade',
            field=models.BooleanField(default=False, verbose_name='نما سازی'),
        ),
        migrations.AlterField(
            model_name='ipsprojects',
            name='is_home_villa',
            field=models.BooleanField(default=False, verbose_name='خانه و ویلا'),
        ),
        migrations.AlterField(
            model_name='ipsprojects',
            name='is_office',
            field=models.BooleanField(default=False, verbose_name='محل کار'),
        ),
        migrations.AlterField(
            model_name='ipsprojects',
            name='is_zero_to_hundred',
            field=models.BooleanField(default=False, verbose_name='صفر تا صد'),
        ),
        migrations.AlterField(
            model_name='ipsprojects',
            name='project_address',
            field=models.CharField(max_length=66, verbose_name='ادرس پروژه'),
        ),
        migrations.AlterField(
            model_name='ipsprojects',
            name='project_details',
            field=models.TextField(verbose_name='توضیحات پروژه'),
        ),
        migrations.AlterField(
            model_name='ipsprojects',
            name='project_img_1',
            field=models.ImageField(blank=True, null=True, upload_to='img/%y%m%d%H%M', verbose_name='عکس 1'),
        ),
        migrations.AlterField(
            model_name='ipsprojects',
            name='project_img_2',
            field=models.ImageField(blank=True, null=True, upload_to='img/%y%m%d%H%M', verbose_name='عکس 2'),
        ),
        migrations.AlterField(
            model_name='ipsprojects',
            name='project_img_3',
            field=models.ImageField(blank=True, null=True, upload_to='img/%y%m%d%H%M', verbose_name='عکس 3'),
        ),
        migrations.AlterField(
            model_name='ipsprojects',
            name='project_img_4',
            field=models.ImageField(blank=True, null=True, upload_to='img/%y%m%d%H%M', verbose_name='عکس 4'),
        ),
        migrations.AlterField(
            model_name='ipsprojects',
            name='project_img_5',
            field=models.ImageField(blank=True, null=True, upload_to='img/%y%m%d%H%M', verbose_name='عکس 5'),
        ),
        migrations.AlterField(
            model_name='ipsprojects',
            name='project_img_6',
            field=models.ImageField(blank=True, null=True, upload_to='img/%y%m%d%H%M', verbose_name='عکس 6'),
        ),
        migrations.AlterField(
            model_name='ipsprojects',
            name='project_main_image',
            field=models.ImageField(upload_to='img/%y%m%d%H%M', verbose_name='عکس اصلی پروژه'),
        ),
        migrations.AlterField(
            model_name='ipsprojects',
            name='project_time_city',
            field=models.CharField(max_length=33, verbose_name='سال و شهر'),
        ),
        migrations.AlterField(
            model_name='ipsprojects',
            name='project_title',
            field=models.CharField(max_length=30, verbose_name='عنوان پروژه'),
        ),
    ]
