# Generated by Django 5.0.6 on 2024-06-17 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConstructionCost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concrete_roof_column_begin', models.CharField(blank=True, max_length=33, null=True, verbose_name='شروع سقف و ستون بتنی')),
                ('concrete_roof_column_begin_en', models.CharField(blank=True, max_length=33, null=True, verbose_name='شروع سقف و ستون بتنی')),
                ('concrete_roof_column_begin_fa', models.CharField(blank=True, max_length=33, null=True, verbose_name='شروع سقف و ستون بتنی')),
                ('concrete_roof_column_end', models.CharField(blank=True, max_length=33, null=True, verbose_name='پایان سقف و ستون بتنی')),
                ('concrete_roof_column_end_en', models.CharField(blank=True, max_length=33, null=True, verbose_name='پایان سقف و ستون بتنی')),
                ('concrete_roof_column_end_fa', models.CharField(blank=True, max_length=33, null=True, verbose_name='پایان سقف و ستون بتنی')),
                ('metal_roof_column_begin', models.CharField(blank=True, max_length=33, null=True, verbose_name='َشروع سقف و ستون فلزی')),
                ('metal_roof_column_begin_en', models.CharField(blank=True, max_length=33, null=True, verbose_name='َشروع سقف و ستون فلزی')),
                ('metal_roof_column_begin_fa', models.CharField(blank=True, max_length=33, null=True, verbose_name='َشروع سقف و ستون فلزی')),
                ('metal_roof_column_end', models.CharField(blank=True, max_length=33, null=True, verbose_name='پایان سقف و ستون فلزی')),
                ('metal_roof_column_end_en', models.CharField(blank=True, max_length=33, null=True, verbose_name='پایان سقف و ستون فلزی')),
                ('metal_roof_column_end_fa', models.CharField(blank=True, max_length=33, null=True, verbose_name='پایان سقف و ستون فلزی')),
                ('hardening_begin', models.CharField(blank=True, max_length=33, null=True, verbose_name='شروع سفت کاری')),
                ('hardening_begin_en', models.CharField(blank=True, max_length=33, null=True, verbose_name='شروع سفت کاری')),
                ('hardening_begin_fa', models.CharField(blank=True, max_length=33, null=True, verbose_name='شروع سفت کاری')),
                ('hardening_end', models.CharField(blank=True, max_length=33, null=True, verbose_name='پایان سفت کاری')),
                ('hardening_end_en', models.CharField(blank=True, max_length=33, null=True, verbose_name='پایان سفت کاری')),
                ('hardening_end_fa', models.CharField(blank=True, max_length=33, null=True, verbose_name='پایان سفت کاری')),
                ('joinery_begin', models.CharField(blank=True, max_length=33, null=True, verbose_name='شروع نازک کاری')),
                ('joinery_begin_en', models.CharField(blank=True, max_length=33, null=True, verbose_name='شروع نازک کاری')),
                ('joinery_begin_fa', models.CharField(blank=True, max_length=33, null=True, verbose_name='شروع نازک کاری')),
                ('construction_with_materials_begin', models.CharField(blank=True, max_length=33, null=True, verbose_name='شروع ساختمان سازی با مصالح')),
                ('construction_with_materials_begin_en', models.CharField(blank=True, max_length=33, null=True, verbose_name='شروع ساختمان سازی با مصالح')),
                ('construction_with_materials_begin_fa', models.CharField(blank=True, max_length=33, null=True, verbose_name='شروع ساختمان سازی با مصالح')),
                ('construction_with_materials_end', models.CharField(blank=True, max_length=33, null=True, verbose_name='پایان ساختمان سازی با مصالح')),
                ('construction_with_materials_end_en', models.CharField(blank=True, max_length=33, null=True, verbose_name='پایان ساختمان سازی با مصالح')),
                ('construction_with_materials_end_fa', models.CharField(blank=True, max_length=33, null=True, verbose_name='پایان ساختمان سازی با مصالح')),
                ('construction_without_materials_begin', models.CharField(blank=True, max_length=33, null=True, verbose_name='شروع ساختمان سازی بدون مصالح')),
                ('construction_without_materials_begin_en', models.CharField(blank=True, max_length=33, null=True, verbose_name='شروع ساختمان سازی بدون مصالح')),
                ('construction_without_materials_begin_fa', models.CharField(blank=True, max_length=33, null=True, verbose_name='شروع ساختمان سازی بدون مصالح')),
                ('construction_without_materials_example_begin', models.CharField(blank=True, max_length=33, null=True, verbose_name='مثال شروع ساختمان سازی بدون مصالح')),
                ('construction_without_materials_example_begin_en', models.CharField(blank=True, max_length=33, null=True, verbose_name='مثال شروع ساختمان سازی بدون مصالح')),
                ('construction_without_materials_example_begin_fa', models.CharField(blank=True, max_length=33, null=True, verbose_name='مثال شروع ساختمان سازی بدون مصالح')),
                ('construction_without_materials_example_end', models.CharField(blank=True, max_length=33, null=True, verbose_name='مثال پایان ساختمان سازی بدون مصالح')),
                ('construction_without_materials_example_end_en', models.CharField(blank=True, max_length=33, null=True, verbose_name='مثال پایان ساختمان سازی بدون مصالح')),
                ('construction_without_materials_example_end_fa', models.CharField(blank=True, max_length=33, null=True, verbose_name='مثال پایان ساختمان سازی بدون مصالح')),
                ('created_time', models.DateTimeField(auto_now=True)),
                ('created_time_en', models.DateTimeField(auto_now=True, null=True)),
                ('created_time_fa', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'verbose_name': 'قیمت ساختمان سازی',
                'verbose_name_plural': 'قیمت های ساختمان سازی',
            },
        ),
    ]
