# Generated by Django 5.0.6 on 2024-06-17 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact_us', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactus',
            options={'verbose_name': 'ارتباط', 'verbose_name_plural': 'ارتباط ها'},
        ),
        migrations.AlterField(
            model_name='contactus',
            name='message',
            field=models.TextField(blank=True, null=True, verbose_name='پیام'),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='name',
            field=models.CharField(max_length=66, verbose_name='نام و نام خانوادگی'),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='number',
            field=models.CharField(max_length=14, verbose_name='شماره تماس'),
        ),
    ]
